### ISSUE TITLE
 Failed to find mytragetname from build log in project's targets: [list of targets]

### ISSUE THREAD

**Issue by magicalc0der** [veracode/gen-ir#20]
I have two targets in the project that use the same source files / assets but have different names and use different configs. Let's name them **mytragetname** and **mytragetname2**   Starting from `gen-ir` > 0.3.4 I am getting the error 

> 2023-04-10 20:58:31 +0000 [gen_ir/GenIR.swift:186 generateTargets(project:log:)] [!] Failed to find mytragetname from build log in project's targets: ["few other targets"]
 
 if I enable debug output I see the following message
 
 > 2023-04-10T21:58:31+0100 debug com.veracode.PBXProjParser : [PBXProjParser] Clash in path name (mytragetname2) for target: (mytragetname2). 
 
 Everything was working all right with `gen-ir` v0.3.3 or  v0.3.4

**Comment by NinjaLikesCheez** [comment]
Hi, I've started some of the testing to ensure this change doesn't break anything. If you'd like to test against this branch and let me know if it resolves your issue that would be great!

**Comment by NinjaLikesCheez** [comment]
You'll need to build locally

**Comment by magicalc0der** [comment]
the version built from the branch worked for me.

**Comment by magicalc0der** [comment]
are you planning to merge it and release a new version?

**Comment by NinjaLikesCheez** [comment]
I plan on doing this today - just in the final stages of testing

**Comment by NinjaLikesCheez** [comment]
I think once we get to a stable 1.0 version that would make sense, the changes between 0.2.x & 0.3.x were substantial and I wouldn't want someone pinning an older version which misses out on the features & fixes. 

I'd rather learn about these issues early and fix them :D In the meantime, I'll open another issue with the request so it doesn't get forgotten about.

**Comment by NinjaLikesCheez** [comment]
Will be released to brew when https://github.com/veracode/homebrew-tap/pull/20 merges
