### ISSUE TITLE
the latest release doesn't generate files for the main target

### ISSUE THREAD

**Issue by magicalc0der** [veracode/gen-ir#31]
After update to v0.3.9 the files for the main app target does not get generated. Please see screen attached for the resulted archive
It does generate data for the second app target but it should be for the first one. There is no way to specify target that I can see in the utility help. 

![veracode](https://github.com/veracode/gen-ir/assets/48348637/da3bf1da-86d2-4a03-b124-f8a604aac87b)

One of the previous versions the one that has this #20 fix, I reckon it was 0.3.7, was working properly

**Comment by NinjaLikesCheez** [comment]
That's certainly odd - I'll dig in a little and see what changed. As for which target is selected, it should be whatever was built as part of your `xcodebuild` command.

**Comment by magicalc0der** [comment]
I am not quite sure how you identify the target in this case. I pass a scheme to build the app and the target is inside the scheme. I can't see target name when I skim through the build log

**Comment by NinjaLikesCheez** [comment]
Interesting - could you describe how the project & scheme are made up so I can try to replicate this in a test app?

**Comment by magicalc0der** [comment]
The app has a few targets. The main app target, copy of the app target with some additional functionality for internal purposes and tests targets (unit & UI tests). The main target has several configurations (schemes) and the build process is controlled by schemes. 

build command looks as it follows:

`xcodebuild -scheme SchemeName -project ./project.xcodeproj -configuration "configuration" -destination generic/platform=iOS -archivePath ./build/archive/archive.xcarchive BUNDLE_IDENTIFIER=BUNDLE_IDENTIFIER PRODUCT_BUNDLE_IDENTIFIER=PRODUCT_BUNDLE_IDENTIFIER "PROVISIONING_PROFILE_SPECIFIER=PROVISIONING_PROFILE_SPECIFIER" DEVELOPMENT_TEAM=DEVELOPMENT_TEAM ENABLE_BITCODE=NO archive `

**Comment by NinjaLikesCheez** [comment]
Thanks for the description, I'll try create a test app to replicate this when I have some time later in the week
