### ISSUE TITLE
The value of buildCachePath is invalid when build in Azure DevOps

### ISSUE THREAD

**Issue by tranquang9a1** [veracode/gen-ir#36]
I have build my iOS project in Azure DevOps.

In log file, 
`Build description signature: 98d19e9ff8db24dd1f55cb46bdda2032
Build description path: /Users/runner/Library/Developer/Xcode/DerivedData/App-ramdomvalue/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/XCBuildData/randomvalue-desc.xcbuild`

Look like after this https://github.com/veracode/gen-ir/blob/main/Sources/GenIR/XcodeLogParser.swift#L90 execute, the value of buildCachePath is /Users/runner/Library/Developer/Xcode/

So it happened error:

`Expected exactly one target folder at path: file:///Users/runner/Library/Developer/Xcode/Intermediates.noindex/ArchiveIntermediates, but found: []. Please manually clear your derived data."`

**Comment by jayanthb007** [comment]
I have the same issue. Is there any fix available soon or are there any workarounds?

**Comment by NinjaLikesCheez** [comment]
Thank you for raising this. 

An interim workaround should be to manually clear derived data for your project. 

I should have a fix for this early next week.

**Comment by tranquang9a1** [comment]
I’m not sure I understand what you mean since this is the first time I work with iOS and Veracode. Could you please give me guidance to implement in Azure DevOps

**Comment by jayanthb007** [comment]
> Thank you for raising this.
> 
> An interim workaround should be to manually clear derived data for your project.
> 
> I should have a fix for this early next week.

Thanks for the quick response. When I delete the folder it is complaining about in gen-ir step it generates Bitcode however veracode platform cannot scan the archive generated after deleting the DerivedData. No supporting files or PDB files error. 

Would really appreciate if you can provide a quick fix or a way to rollback to the previous version of gen-ir.
Thank you

**Comment by NinjaLikesCheez** [comment]
About the version rollbacks, I've opened #37 so it's on our list for investigation!

I'll release a patch later today to resolve this issue. 

For issues with the Veracode Platform I'd ask you go through the support channel as it allows us to investigate deeper.

Thanks!

**Comment by NinjaLikesCheez** [comment]
Will be released when https://github.com/veracode/homebrew-tap/pull/25 merges

**Comment by tranquang9a1** [comment]
I'm not sure it fixed yet but when tried new version, the same error happened

tooManyDirectories("Expected exactly one target folder at path: file:///Users/runner/Library/Developer/Xcode/Intermediates.noindex/ArchiveIntermediates, but found: [].\nPlease manually clear your derived data before rebuilding.")

**Comment by jayanthb007** [comment]
I’m still getting the same error too. @NinjaLikesCheez: any chance you could rollback to the working version 0.3.11 or provide us a way to download that version soon? Really appreciate your help as we are currently blocked from a release.

**Comment by NinjaLikesCheez** [comment]
> I'm not sure it fixed yet but when tried new version, the same error happened
> 
> tooManyDirectories("Expected exactly one target folder at path: file:///Users/runner/Library/Developer/Xcode/Intermediates.noindex/ArchiveIntermediates, but found: [].\nPlease manually clear your derived data before rebuilding.")

Hm. did you rebuild your project? Are you doing an archive build or a regular build with `xcodebuild`?

> I’m still getting the same error too. @NinjaLikesCheez: any chance you could rollback to the working version 0.3.11 or provide us a way to download that version soon? Really appreciate your help as we are currently blocked from a release.

For now, you can manually roll back by cloning the git repo, building the project, and using the result. I'll add the commands below:

```bash
git clone git@github.com/veracode/gen-ir.git
cd gen-ir
git fetch --all --tags
git checkout 0.3.11
swift build -c release
export PATH="${PWD}/.build/release/:$PATH"

# You can now use gen-ir 0.3.11 in this shell
gen-ir --version
```

**Comment by jayanthb007** [comment]
@NinjaLikesCheez any idea why it is still failing?

**Comment by jayanthb007** [comment]
No problem, thanks for the quick turnaround. Any idea how long it will take for the homebrew to recognize the new release? It is still downloading 0.4.1

**Comment by jayanthb007** [comment]
Was able to get 0.4.2 and that got rid of the error. Thanks again!

**Comment by NinjaLikesCheez** [comment]
No problem! Thank you both for the patience and your help in debugging the issue!
