### ISSUE TITLE
Logger output buffered when piping

### ISSUE THREAD

**Issue by kjcjohnson** [veracode/gen-ir#58]
The `print` function in Swift is fully buffered by default, so when piping `gen-ir` output, the logger outputs get delayed and, occasionally, split.

**Example (`gen-ir` 0.5.0-alpha)**
In a CI script, I want to save off the output of `gen-ir` into a separate file, as well as see the progress in the console. I call `gen-ir` in a pipe to do so:
```bash
set -o pipefail && gen-ir <build-log> <xcarchive> --project-path <workspace> | tee gen-ir.log
```
Here, each `Running command (clang) XX of YY. Target modules processed: ZZ` no longer is printed in real time, until enough are printed to fill the buffer. Occasionally, we'll also see, e.g., `Running comm` or similar split lines, when the full line doesn't fit inside the IO buffer.

**Impact**
Makes it more difficult to track the progress of `gen-ir`. In our case, it takes ~15 minutes to process everything, so it would be nice to have the real-time updates instead of waiting for the buffer to fill, which takes ~30s - ~1min.

**Suggested Fix**
Flush stdout after printing a log message. Not sure what other ways there are, but adding `fflush(__stdoutp)` after the print call in StdoutLogHandler.swift did it for me.

https://github.com/veracode/gen-ir/blob/e8da32c646eef95bfe0118264b3d5eb2554e70ac/Sources/GenIR/StdoutLogHandler.swift#L29-L43

**Comment by NinjaLikesCheez** [comment]
This will be addressed in #62 (https://github.com/veracode/gen-ir/pull/62/files#diff-fb10c82a336be9dc08b5db062c7270903e82bb9865d8e8e4aa1a5924ea469ca3) :)
