### ISSUE TITLE
Recent Gen IR updates causing potential inconsistencies

### ISSUE THREAD

**Issue by nicolastorregrosa** [veracode/gen-ir#72]
Currently using Gen IR for a company iOS solution that requires Veracode scanning. The Gen IR install and execution has been integrated into our Azure DevOps pipelines using Microsoft Hosted Agents and was successfully running against our iOS workspace archives. However, it appears recent updates to Gen IR have caused new requirements of the tool usage which are inconsistent with current documentation around Gen IR and Veracode. After updating the Azure DevOps pipelines to use macOS 14 with Xcode 15.4, Gen IR is back to successfully executing and generating the LLVM IR for the iOS solution. 

With that, I have documented potential inconsistencies with the latest version of Gen IR and it's usage:
NOTE: This is based on testing with Azure DevOps build pipelines using Microsoft Hosted Agents which requires a fresh install of Gen IR for each build.
Issues:
- Latest Gen IR version is only supported with macOS 14 on Xcode 15.3 and greater.
    - Required for included Xcode Command Line tools (see example output below)
    - Required for Swift Tools version 5.10 (see example output below)
        - Link to Xcode Minimum requirements and supported SDKs: https://developer.apple.com/support/xcode/#:~:text=Minimum%20requirements%20and%20supported%C2%A0SDKs
    - Documentation states:
        - To build the tool, you'll need Xcode 14 and macOS 12.5 or greater.
        - To install and run the tool, you'll need Homebrew, Xcode, and macOS 12 or greater.
        - https://github.com/veracode/gen-ir?tab=readme-ov-file#prerequisites
     - Example output using Azure DevOps macOS 13 image running Xcode 15.2
```
==> Installing gen-ir from veracode/tap
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Settings.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  [https://developer.apple.com/download/all/.](https://developer.apple.com/download/all/)
You should download the Command Line Tools for Xcode 15.2.

==> swift build -c release --disable-sandbox
Last 15 lines from /Users/runner/Library/Logs/Homebrew/gen-ir/01.swift:
2024-09-16 14:51:59 +0000

swift
build
-c
release
--disable-sandbox

warning: /Users/runner/Library/org.swift.swiftpm/configuration is not accessible or not writable, disabling user-level cache features.
warning: /Users/runner/Library/org.swift.swiftpm/security is not accessible or not writable, disabling user-level cache features.
error: package 'pif' is using Swift tools version 5.10.0 but the installed version is 5.9.0

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/veracode/homebrew-tap/issues


Error: A newer Command Line Tools release is available.
Update them from Software Update in System Settings.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  [https://developer.apple.com/download/all/.](https://developer.apple.com/download/all/)
You should download the Command Line Tools for Xcode 15.2.

/Users/runner/work/_temp/31fb54f0-d6d8-42cb-8a33-a0da237640ce.sh: line 10: gen-ir: command not found
```
- Gen IR documentation inconsistencies:
    - Gen IR states Xcode clean must occur before the Xcode build, but does not explicitly state they must be separate calls.
        - Example output from command: Ensure a clean build **AND** ensure `xcodebuild clean` happens separately from `xcodebuild archive` command")
- Veracode documentation inconsistencies:
    - For iOS packaging, Veracode states to run `gen-ir` with `—project-path` argument. However, latest version of Gen IR shows the `—project-path` argument has been deprecated.
        - https://docs.veracode.com/r/Use_xcodebuild_to_Package_iOS_and_tvOS_Apps

If there are any inaccuracies and/or misunderstandings from above, I can certainly update any of the information as needed and/or the issue can be closed. With that, any feedback on this would be greatly appreciated.

**Comment by NinjaLikesCheez** [comment]
Thank you very much for such a detailed report! You're spot on with all your points - thank you for taking the time to alert us to them!

I have opened an internal merge request with our documentation team to update the docs.veracode.com site to remove the deprecated CLI option and I've opened #74 to address the doc inconsistency in this repo. I will post an update here when that makes it to production.

@bmxav has opened #73 to fix the Xcode building issues.

**Comment by bmxav** [comment]
Thanks for bringing this to our attention! I will be working on getting a 0.5.1 patch release out today with the fix.

**Comment by NinjaLikesCheez** [comment]
The docs.veracode.com changes are live https://docs.veracode.com/r/Generate_IR_to_Package_iOS_and_tvOS_Apps

**Comment by bmxav** [comment]
@nicolastorregrosa v0.5.1 of `gen-ir` has been made available, which should fix the issue with the minimum versions (macOS 12 and Xcode 14).
